#!/bin/bash
echo "=== Testando cd ==="
echo ""
echo "Teste 1: pwd inicial"
echo "pwd"
echo ""
echo "Teste 2: cd /tmp"
echo "cd /tmp"
echo "pwd"
echo ""
echo "Teste 3: cd .."
echo "cd .."
echo "pwd"
echo ""
echo "Teste 4: cd ~ (HOME)"
echo "cd ~"
echo "pwd"
echo ""
echo "Teste 5: cd (sem args, deve ir para HOME)"
echo "cd"
echo "pwd"
echo ""
echo "Teste 6: cd - (volta para dir anterior)"
echo "cd /tmp"
echo "cd ~"
echo "cd -"
echo "pwd"
echo ""
echo "Teste 7: cd caminho_invalido (deve dar erro)"
echo "cd /caminho/que/nao/existe"
echo ""
echo "Teste 8: cd com muitos argumentos (deve dar erro)"
echo "cd /tmp /home"
